import * as NBA from 'nba';

export class Player {
	constructor(
        public firstName: string, 
        public lastName: string, 
        public playerId: number, 
        public teamId: number, 
        public fullName: string) {};
    }

export class Players {

	constructor() {}
            
    create( someone: string ) {
        let info = NBA.findPlayer(someone);
        return new Player(info.firstName, info.lastName, info.playerId, info.teamId, info.fullName);             
    }

    static create( someone: string ) {
        let info = NBA.findPlayer(someone);
        return new Player(info.firstName, info.lastName, info.playerId, info.teamId, info.fullName);
    }

    static getStats( someone: any ) {
        let statistics: 
        [ 
            { 
                groupSet: 'Month',
                groupValue: 'October',
                gp: 8,
                w: 5,
                l: 3,
                wPct: 0.625,
                min: 36.3,
                fgm: 8.5,
                fga: 20.1,
                fgPct: 0.422,
                fG3M: 3.4,
                fG3A: 9.8,
                fg3Pct: 0.346,
                ftm: 5.6,
                fta: 7,
                ftPct: 0.804,
                oreb: 0.8,
                dreb: 4,
                reb: 4.8,
                ast: 9.3,
                tov: 5,
                stl: 1.8,
                blk: 0.5,
                blka: 1.5,
                pf: 2.8,
                pfd: 6,
                pts: 26,
                plusMinus: 0.4,
                nbaFantasyPts: 47.3,
                dD2: 3,
                tD3: 1,
                gpRank: 5,
                wRank: 6,
                lRank: 2,
                wPctRank: 6,
                minRank: 2,
                fgmRank: 6,
                fgaRank: 3,
                fgPctRank: 7,
                fg3mRank: 5,
                fg3aRank: 5,
                fg3PctRank: 6,
                ftmRank: 7,
                ftaRank: 7,
                ftPctRank: 7,
                orebRank: 4,
                drebRank: 7,
                rebRank: 6,
                astRank: 2,
                tovRank: 2,
                stlRank: 4,
                blkRank: 6,
                blkaRank: 3,
                pfRank: 2,
                pfdRank: 7,
                ptsRank: 7,
                plusMinusRank: 7,
                nbaFantasyPtsRank: 6,
                dd2Rank: 6,
                td3Rank: 1,
                cfid: 29,
                cfparams: 'October' 
            },{ 
                groupSet: 'Month',
                groupValue: 'November',
                gp: 13,
                w: 12,
                l: 1,
                wPct: 0.923,
                min: 35.7,
                fgm: 10.2,
                fga: 21.7,
                fgPct: 0.468,
                fG3M: 5.2,
                fG3A: 11.9,
                fg3Pct: 0.432,
                ftm: 9.5,
                fta: 10.6,
                ftPct: 0.891,
                oreb: 0.5,
                dreb: 4.9,
                reb: 5.5,
                ast: 10.1,
                tov: 4.4,
                stl: 1.6,
                blk: 0.5,
                blka: 1,
                pf: 2.5,
                pfd: 6.9,
                pts: 34.9,
                plusMinus: 16.4,
                nbaFantasyPts: 58.4,
                dD2: 8,
                tD3: 1,
                gpRank: 2,
                wRank: 1,
                lRank: 4,
                wPctRank: 2,
                minRank: 3,
                fgmRank: 1,
                fgaRank: 1,
                fgPctRank: 2,
                fg3mRank: 1,
                fg3aRank: 1,
                fg3PctRank: 1,
                ftmRank: 2,
                ftaRank: 2,
                ftPctRank: 1,
                orebRank: 5,
                drebRank: 3,
                rebRank: 3,
                astRank: 1,
                tovRank: 3,
                stlRank: 5,
                blkRank: 7,
                blkaRank: 6,
                pfRank: 3,
                pfdRank: 4,
                ptsRank: 1,
                plusMinusRank: 1,
                nbaFantasyPtsRank: 1,
                dd2Rank: 1,
                td3Rank: 1,
                cfid: 29,
                cfparams: 'November' 
            },{ 
                groupSet: 'Month',
                groupValue: 'December',
                gp: 14,
                w: 9,
                l: 5,
                wPct: 0.643,
                min: 36.9,
                fgm: 9.6,
                fga: 21.3,
                fgPct: 0.45,
                fG3M: 3.6,
                fG3A: 9.9,
                fg3Pct: 0.367,
                ftm: 10.8,
                fta: 12.4,
                ftPct: 0.868,
                oreb: 0.3,
                dreb: 4.4,
                reb: 4.7,
                ast: 8.1,
                tov: 4.1,
                stl: 2,
                blk: 0.6,
                blka: 1.7,
                pf: 2.8,
                pfd: 8,
                pts: 33.6,
                plusMinus: 3.1,
                nbaFantasyPts: 55.2,
                dD2: 4,
                tD3: 0,
                gpRank: 1,
                wRank: 4,
                lRank: 1,
                wPctRank: 5,
                minRank: 1,
                fgmRank: 2,
                fgaRank: 2,
                fgPctRank: 3,
                fg3mRank: 4,
                fg3aRank: 4,
                fg3PctRank: 4,
                ftmRank: 1,
                ftaRank: 1,
                ftPctRank: 3,
                orebRank: 6,
                drebRank: 5,
                rebRank: 7,
                astRank: 7,
                tovRank: 6,
                stlRank: 2,
                blkRank: 4,
                blkaRank: 1,
                pfRank: 1,
                pfdRank: 1,
                ptsRank: 2,
                plusMinusRank: 5,
                nbaFantasyPtsRank: 2,
                dd2Rank: 3,
                td3Rank: 5,
                cfid: 29,
                cfparams: 'December' 
            },{ 
                groupSet: 'Month',
                groupValue: 'January',
                gp: 7,
                w: 6,
                l: 1,
                wPct: 0.857,
                min: 35.2,
                fgm: 8.9,
                fga: 20,
                fgPct: 0.443,
                fG3M: 3.7,
                fG3A: 10.1,
                fg3Pct: 0.366,
                ftm: 6.4,
                fta: 7.9,
                ftPct: 0.818,
                oreb: 1,
                dreb: 4.1,
                reb: 5.1,
                ast: 9,
                tov: 4.3,
                stl: 2.1,
                blk: 1.4,
                blka: 1.4,
                pf: 1.7,
                pfd: 6.6,
                pts: 27.9,
                plusMinus: 4.3,
                nbaFantasyPts: 54,
                dD2: 4,
                tD3: 1,
                gpRank: 6,
                wRank: 5,
                lRank: 4,
                wPctRank: 4,
                minRank: 4,
                fgmRank: 3,
                fgaRank: 4,
                fgPctRank: 5,
                fg3mRank: 3,
                fg3aRank: 3,
                fg3PctRank: 5,
                ftmRank: 6,
                ftaRank: 6,
                ftPctRank: 6,
                orebRank: 1,
                drebRank: 6,
                rebRank: 5,
                astRank: 3,
                tovRank: 5,
                stlRank: 1,
                blkRank: 1,
                blkaRank: 4,
                pfRank: 7,
                pfdRank: 5,
                ptsRank: 5,
                plusMinusRank: 4,
                nbaFantasyPtsRank: 3,
                dd2Rank: 3,
                td3Rank: 1,
                cfid: 29,
                cfparams: 'January' 
            },{ 
                groupSet: 'Month',
                groupValue: 'February',
                gp: 12,
                w: 12,
                l: 0,
                wPct: 1,
                min: 34.2,
                fgm: 8.6,
                fga: 19.2,
                fgPct: 0.448,
                fG3M: 4,
                fG3A: 10.8,
                fg3Pct: 0.372,
                ftm: 8.9,
                fta: 10.2,
                ftPct: 0.877,
                oreb: 0.3,
                dreb: 5.4,
                reb: 5.7,
                ast: 8.1,
                tov: 3.9,
                stl: 1.6,
                blk: 0.7,
                blka: 1.2,
                pf: 2.1,
                pfd: 7.2,
                pts: 30.1,
                plusMinus: 11.7,
                nbaFantasyPts: 51.8,
                dD2: 4,
                tD3: 0,
                gpRank: 4,
                wRank: 1,
                lRank: 7,
                wPctRank: 1,
                minRank: 7,
                fgmRank: 5,
                fgaRank: 6,
                fgPctRank: 4,
                fg3mRank: 2,
                fg3aRank: 2,
                fg3PctRank: 3,
                ftmRank: 3,
                ftaRank: 4,
                ftPctRank: 2,
                orebRank: 7,
                drebRank: 2,
                rebRank: 2,
                astRank: 6,
                tovRank: 7,
                stlRank: 6,
                blkRank: 3,
                blkaRank: 5,
                pfRank: 5,
                pfdRank: 2,
                ptsRank: 3,
                plusMinusRank: 2,
                nbaFantasyPtsRank: 5,
                dd2Rank: 3,
                td3Rank: 5,
                cfid: 29,
                cfparams: 'February' },
              { groupSet: 'Month',
                groupValue: 'March',
                gp: 13,
                w: 12,
                l: 1,
                wPct: 0.923,
                min: 34.7,
                fgm: 8.6,
                fga: 19.8,
                fgPct: 0.436,
                fG3M: 2.4,
                fG3A: 8.8,
                fg3Pct: 0.27,
                ftm: 8.8,
                fta: 10.5,
                ftPct: 0.838,
                oreb: 0.8,
                dreb: 5.6,
                reb: 6.4,
                ast: 8.4,
                tov: 4.4,
                stl: 1.9,
                blk: 0.8,
                blka: 1.5,
                pf: 2.1,
                pfd: 7.1,
                pts: 28.4,
                plusMinus: 6.8,
                nbaFantasyPts: 52.3,
                dD2: 6,
                tD3: 1,
                gpRank: 2,
                wRank: 1,
                lRank: 4,
                wPctRank: 2,
                minRank: 5,
                fgmRank: 4,
                fgaRank: 5,
                fgPctRank: 6,
                fg3mRank: 7,
                fg3aRank: 6,
                fg3PctRank: 7,
                ftmRank: 4,
                ftaRank: 3,
                ftPctRank: 5,
                orebRank: 3,
                drebRank: 1,
                rebRank: 1,
                astRank: 5,
                tovRank: 3,
                stlRank: 3,
                blkRank: 2,
                blkaRank: 2,
                pfRank: 6,
                pfdRank: 3,
                ptsRank: 4,
                plusMinusRank: 3,
                nbaFantasyPtsRank: 4,
                dd2Rank: 2,
                td3Rank: 1,
                cfid: 29,
                cfparams: 'March' },
              { groupSet: 'Month',
                groupValue: 'April',
                gp: 5,
                w: 3,
                l: 2,
                wPct: 0.6,
                min: 34.3,
                fgm: 8,
                fga: 16.2,
                fgPct: 0.494,
                fG3M: 3,
                fG3A: 7,
                fg3Pct: 0.429,
                ftm: 7.8,
                fta: 9.2,
                ftPct: 0.848,
                oreb: 0.8,
                dreb: 4.6,
                reb: 5.4,
                ast: 8.6,
                tov: 5.4,
                stl: 0.8,
                blk: 0.6,
                blka: 1,
                pf: 2.2,
                pfd: 6.2,
                pts: 26.8,
                plusMinus: 1.4,
                nbaFantasyPts: 45,
                dD2: 2,
                tD3: 0,
                gpRank: 7,
                wRank: 7,
                lRank: 3,
                wPctRank: 7,
                minRank: 6,
                fgmRank: 7,
                fgaRank: 7,
                fgPctRank: 1,
                fg3mRank: 6,
                fg3aRank: 7,
                fg3PctRank: 2,
                ftmRank: 5,
                ftaRank: 5,
                ftPctRank: 4,
                orebRank: 2,
                drebRank: 4,
                rebRank: 4,
                astRank: 4,
                tovRank: 1,
                stlRank: 7,
                blkRank: 5,
                blkaRank: 6,
                pfRank: 4,
                pfdRank: 6,
                ptsRank: 6,
                plusMinusRank: 6,
                nbaFantasyPtsRank: 7,
                dd2Rank: 7,
                td3Rank: 5,
                cfid: 29,
                cfparams: 'April' } 
        ];

        let player = NBA.stats.playerSplits({ PlayerID: someone.playerId })
                        .then(
                            function (res) {
                                statistics = res.monthPlayerDashboard;
                                console.dir(statistics);
                            },
                            function (err) {
                                console.log(err);
                            })
    }

}